const mockbusiness = [
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90},   {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
  {name: 'MarginOtto Pizzeria', 
  image: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=', 
  address: '1010 Paddington Way', 
  city: 'Bordertown', 
  state: 'NY', 
  zipcode: '10101', 
  category: 'Italian', 
  rating: 4.5, 
  review_count: 90}, 
]

export default mockbusiness; 